### ISSUE TITLE
Mismatched Version

### ISSUE THREAD

**Issue by Hephaest** [growthbook/coderefs-action#1]
### Description

I just came from the latest GrowthBook [updates](https://medium.com/growth-book/growthbook-version-2-8-0f4e97ce5e5d) and tried to apply it to our own CI workflows.

I followed the README instructions but met unexpected issues:
![image](https://github.com/growthbook/coderefs-action/assets/37981444/289518e8-91d8-4481-8d8d-02c2762250e0)

### Root Cause

I downloaded the source code for 2.11.5-13 and found the `action.yml` didn't match the specifications in README:
<img width="652" alt="image" src="https://github.com/growthbook/coderefs-action/assets/37981444/8714e83f-9005-4dcd-95fc-0bf806fcb03b">

### Demo
I tried adding a new release to my repo, and it worked out!
![image](https://github.com/growthbook/coderefs-action/assets/37981444/a62f9db5-652e-4596-bada-457950284cbc)

**Comment by bttf** [comment]
Thanks for catching this! Our latest release wasn't up-to-date. We just pushed a `-14` version that should reflect latest.
